intent_script:
  plexstreamtv:
    speech:
      text: "{{ shows }} is playing now."
    action:
      - service: media_player.play_media
        continue_on_error: true
        target:
          entity_id: "{{ media_player }}"
        data: 
          media_content_type: tvshow
          media_content_id: 'plex://{"library_name": "TV", "show.title": "{{ shows }}", "episode.unwatched": true, "allow_multiple": 1 }'
      - wait_template: "{{ is_state('sensor.deathbot64_state', 'playing') }}"
        timeout: "00:00:12"
      - if: 
          - "{{ not wait.completed }}"
        then:
          - service: media_player.play_media
            target:
              entity_id: "{{ media_player }}"
            data: 
              media_content_type: tvshow
              media_content_id: 'plex://{"library_name": "TV", "show.title": "{{ shows }}", "allow_multiple": 1 }'
        else:
          - stop: "" 
  plexrandomtv:
    speech:
      text: Starting the playback in a moment.
    action:
      - service: media_player.play_media
        target:
          entity_id: "{{ media_player }}"
        data: 
          media_content_type: tvshow
          media_content_id: 'plex://{"library_name": "TV", "show.title": "{{ shows }}", "shuffle": "1", "allow_multiple": 1 }' 
  plexrandomseason:
    speech:
      text: Starting the playback in a moment.
    action:
      - service: media_player.play_media
        target:
          entity_id: "{{ media_player }}"
        data: 
          media_content_type: tvshow
          media_content_id: 'plex://{"library_name": "TV", "show.title": "{{ shows }}", "season_number": "{{ season }}", "shuffle": "1", "allow_multiple": 1 }' 
  plexspecificepisode:
    speech:
      text: Starting the playback in a moment.
    action:
      - service: media_player.play_media
        target:
          entity_id: "{{ media_player }}"
        data: 
          media_content_type: tvshow
          media_content_id: 'plex://{"library_name": "TV", "show.title": "{{ shows }}", "season_number": "{{ season }}", "episode_number": "{{ episode }}" }'   
  plexmovie:
    speech:
      text: Starting the playback in a moment.
    action:
      - service: media_player.play_media
        target:
          entity_id: "{{ media_player }}"
        data: 
          media_content_type: movie
          media_content_id: 'plex://{"library_name": "Movies", "title": "{{ movie }}" }'   
  plexplaylist:
    speech:
      text: Starting the playback in a moment.
    action:
      - service: media_player.play_media
        target:
          entity_id: "{{ media_player }}"
        data: 
          media_content_type: playlist
          media_content_id: 'plex://901a9a91c139e8299145175bbc84754596768d3f/{{ playlist }}?shuffle=1'   
  plexcurrentshow:
    speech:
      text: Starting the playback in a moment.
    action:
      - service: media_player.play_media
        target:
          entity_id: "{{ media_player }}"
        data: 
          media_content_type: playlist
          media_content_id: 'plex://901a9a91c139e8299145175bbc84754596768d3f/1643426'   
  plexpause:
    speech:
      text: Pausing the playback in a moment.
    action:
      - service: media_player.media_pause
        target:
          entity_id: "{{ media_player }}"
        data: {}    
  plexresume:
    speech:
      text: Resuming the playback in a moment.
    action:
      - service: media_player.media_play
        target:
          entity_id: "{{ media_player }}" 
        data: {}    
  plexstop:
    speech:
      text: Stopping the playback in a moment.
    action:
      - service: media_player.media_stop
        target:
          entity_id: "{{ media_player }}" 
        data: {}
